# Solving Linear Systems of Equations
---

## System of equations

Consider a system of equations for $w$, $x$, $y$, and $z$, written in matrix form as

$$
\left[
  \begin{array}{rrrr}
    2 &  1 &  4 &  1 \\
    3 &  4 & -1 & -1 \\
    1 & -4 &  1 &  5 \\
    2 & -2 &  1 &  3
  \end{array}
\right]
\left[
  \begin{array}{c}
    w \\
    x \\
    y \\
    z
  \end{array}
\right]
=
\left[
  \begin{array}{r}
    -4 \\
     3 \\
     9 \\
     7
  \end{array}
\right]
$$

This can be written as $\mathbf{A}\vec{\mathbf{x}} = \vec{\mathbf{b}}$ where

$$
  \mathbf{A} = 
  \left[
  \begin{array}{rrrr}
    2 &  1 &  4 &  1 \\
    3 &  4 & -1 & -1 \\
    1 & -4 &  1 &  5 \\
    2 & -2 &  1 &  3
  \end{array}
  \right] 
  \quad\quad,\quad\quad
  \vec{\mathbf{x}} = \left[
  \begin{array}{c}
    w \\
    x \\
    y \\
    z
  \end{array}
  \right]
  \quad\quad\text{, and}\quad\quad
  \vec{\mathbf{b}} = 
  \left[
  \begin{array}{r}
    -4 \\
     3 \\
     9 \\
     7
  \end{array}
  \right].
$$

In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
A = np.array([[2, 1, 4, 1], 
              [3, 4, -1, -1],
              [1, -4, 1, 5],
              [2, -2, 1, 3]])
A

array([[ 2,  1,  4,  1],
       [ 3,  4, -1, -1],
       [ 1, -4,  1,  5],
       [ 2, -2,  1,  3]])

In [3]:
b = np.array([[-4], 
              [3], 
              [9], 
              [7]])
b

array([[-4],
       [ 3],
       [ 9],
       [ 7]])

## Solving using solve(A, b)

In [4]:
la.solve(A,b)

array([[ 2.],
       [-1.],
       [-2.],
       [ 1.]])

## Solving via LU decomposition

The matrix $\mathbf{A}$ can be decomposed as $\mathbf{A} = \mathbf{P}\mathbf{L}\mathbf{U}$, where $\mathbf{U}$ is an upper triangular matrix, $\mathbf{L}$ is a lower triangular matrix, and $\mathbf{P}$ is a permutation matrix that keeps track of the row permutations (i.e., pivoting) performed when calculating $\mathbf{L}$ and $\mathbf{U}$. Making this replacement, the new matrix equation becomes $\mathbf{P}\mathbf{L}\mathbf{U}\vec{\mathbf{x}} = \vec{\mathbf{b}}$ or equivalently

$$
\mathbf{L}\mathbf{U}\vec{\mathbf{x}} = \mathbf{P}^{-1}\vec{\mathbf{b}}
$$

Letting $\mathbf{U}\vec{\mathbf{x}} = \vec{\mathbf{y}}$ yields

$$
\mathbf{L}\vec{\mathbf{y}} = \mathbf{P}^{-1}\vec{\mathbf{b}} 
$$

which, because $\mathbf{L}$ is lower triangular, can quickly be solved for $\vec{\mathbf{y}}$ using forward substitution. With $\vec{\mathbf{y}}$ known, and because $\mathbf{U}$ is upper triangular, the equation

$$
\mathbf{U}\vec{\mathbf{x}} = \vec{\mathbf{y}} 
$$

can be quickly solved for $\vec{\mathbf{x}}$ using backward substitution.

In [6]:
P, L, U = la.lu(A)
print(P) # permutation matrix
print(L) # lower triangular
print(U) # upper triangular

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
[[1.         0.         0.         0.        ]
 [0.33333333 1.         0.         0.        ]
 [0.66666667 0.3125     1.         0.        ]
 [0.66666667 0.875      0.11764706 1.        ]]
[[ 3.00000000e+00  4.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00 -5.33333333e+00  1.33333333e+00  5.33333333e+00]
 [ 0.00000000e+00  0.00000000e+00  4.25000000e+00  1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00]]


In [7]:
P @ L @ U

array([[ 2.,  1.,  4.,  1.],
       [ 3.,  4., -1., -1.],
       [ 1., -4.,  1.,  5.],
       [ 2., -2.,  1.,  3.]])

In [8]:
## method 1
x = la.solve(P@L@U, b)
x

array([[ 2.],
       [-1.],
       [-2.],
       [ 1.]])

In [9]:
## method 2
y = la.solve(P@L, b)
x = la.solve(U,y)
x

array([[ 2.],
       [-1.],
       [-2.],
       [ 1.]])

In [11]:
## method 3
bnew = la.inv(P) @ b
y = la.solve(L, bnew)
x = la.solve(U,y)
x

array([[ 2.],
       [-1.],
       [-2.],
       [ 1.]])